name: Deploy to Nginx

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Deploy to EC2
      env:
        EC2_USER: ubuntu
        EC2_HOST: ec2-18-134-245-65.eu-west-2.compute.amazonaws.com
        EC2_SSH_KEY: ${{ secrets.EC2_SSH_KEY }}
      run: |
        ssh -i ${{ env. EC2_SSH_KEY}} ${{ env.EC2_USER }}@${{ env.EC2_HOST }} 'sudo rm /var/www/html/index.nginx-debian.html'
        scp -i ${{ env.EC2_SSH_KEY }} index.html ${{ env.EC2_USER }}@${{ env.EC2_HOST }}:/var/www/html/index.html
        ssh -i ${{ env.EC2_SSH_KEY }} ${{ env.EC2_USER }}@${{ env.EC2_HOST }} 'sudo systemctl restart nginx'
